
export const USER_INFORMATION_REQUEST = '@@user/USER_INFORMATION_REQUEST';

export const USER_INFORMATION_SUCCESS = '@@user/USER_INFORMATION_SUCCESS';

export const USER_INFORMATION_ERROR = '@@user/USER_INFORMATION_ERROR';