
export const USER_INFORMATION_REQUEST = 'USER_INFORMATION_REQUEST';

export const USER_INFORMATION_SUCCESS = 'USER_INFORMATION_SUCCESS';

export const USER_INFORMATION_ERROR = 'USER_INFORMATION_ERROR';